library(readxl)
library(ggplot2)
library(psych)

#sink('/Users/jennygilbert/Documents/betaseries_bevel/5_analysis/results/node_analysis_output.txt')

df_long <- read.csv("/Users/jennygilbert/Documents/betaseries_bevel/5_analysis/results/network/node_metrics_by_sub_long_WEIGHTED.csv")
names(df_long)

describe(df)

#Select Clustering
df_clust <- df_long[which(df_long$metric == 'clustering'), ]
describeBy(df_clust, df_clust$condition)
t.test(module0_mean ~ condition, data = df_clust)
t.test(module1_mean ~ condition, data = df_clust)
t.test(module2_mean ~ condition, data = df_clust)
t.test(module3_mean ~ condition, data = df_clust)
t.test(module4_mean ~ condition, data = df_clust)
t.test(module5_mean ~ condition, data = df_clust)
t.test(module6_mean ~ condition, data = df_clust)
t.test(module7_mean ~ condition, data = df_clust)
t.test(module8_mean ~ condition, data = df_clust)

t.test(Amygdala_L ~ condition, data = df_clust)
t.test(Amygdala_R ~ condition, data = df_clust)
t.test(Dorsal_striatum_L ~ condition, data = df_clust)
t.test(Dorsal_striatum_R ~ condition, data = df_clust)
t.test(Fusiform_gyrus_L ~ condition, data = df_clust)
t.test(Fusiform_gyrus_R ~ condition, data = df_clust)
t.test(Hippocampus_L ~ condition, data = df_clust)
t.test(Hippocampus_R ~ condition, data = df_clust)
t.test(Insula_L ~ condition, data = df_clust)
t.test(Insula_R ~ condition, data = df_clust)
t.test(Intracalcarine_cortex_L ~ condition, data = df_clust)
t.test(Intracalcarine_cortex_R ~ condition, data = df_clust)
t.test(lOFC_L ~ condition, data = df_clust)
t.test(lOFC_R ~ condition, data = df_clust)
t.test(mOFC_L ~ condition, data = df_clust)
t.test(mOFC_R ~ condition, data = df_clust)
t.test(Oral_somatosensory_cortex_R ~ condition, data = df_clust)
t.test(Oral_somatosensory_cortex_L ~ condition, data = df_clust)
t.test(Precuneus_L ~ condition, data = df_clust)
t.test(Precuneus_R ~ condition, data = df_clust)
t.test(Ventral_striatum_L ~ condition, data = df_clust)
t.test(Ventral_striatum_R ~ condition, data = df_clust)
t.test(vlPFC_L ~ condition, data = df_clust)
t.test(vlPFC_R ~ condition, data = df_clust)
t.test(vlThalamus_L ~ condition, data = df_clust)
t.test(vlThalamus_R ~ condition, data = df_clust)
t.test(vmPFC_L ~ condition, data = df_clust)
t.test(vmPFC_R ~ condition, data = df_clust)

#Select Centrality
df_cent <- df_long[which(df_long$metric == 'centrality'), ]
describeBy(df_cent, df_cent$condition)
t.test(module0_mean ~ condition, data = df_cent)
t.test(module1_mean ~ condition, data = df_cent)
t.test(module2_mean ~ condition, data = df_cent)
t.test(module3_mean ~ condition, data = df_cent)
t.test(module4_mean ~ condition, data = df_cent)
t.test(module5_mean ~ condition, data = df_cent)
t.test(module6_mean ~ condition, data = df_cent)
t.test(module7_mean ~ condition, data = df_cent)
t.test(module8_mean ~ condition, data = df_cent)

#Test by node
t.test(Amygdala_L ~ condition, data = df_cent)
t.test(Amygdala_L ~ condition, data = df_cent)
t.test(Amygdala_R ~ condition, data = df_cent)
t.test(Dorsal_striatum_L ~ condition, data = df_cent)
t.test(Dorsal_striatum_R ~ condition, data = df_cent)
t.test(Fusiform_gyrus_L ~ condition, data = df_cent)
t.test(Fusiform_gyrus_R ~ condition, data = df_cent)
t.test(Hippocampus_L ~ condition, data = df_cent)
t.test(Hippocampus_R ~ condition, data = df_cent)
t.test(Insula_L ~ condition, data = df_cent)
t.test(Insula_R ~ condition, data = df_cent)
t.test(Intracalcarine_cortex_L ~ condition, data = df_cent)
t.test(Intracalcarine_cortex_R ~ condition, data = df_cent)
t.test(lOFC_L ~ condition, data = df_cent)
t.test(lOFC_R ~ condition, data = df_cent)
t.test(mOFC_L ~ condition, data = df_cent)
t.test(mOFC_R ~ condition, data = df_cent)
t.test(Oral_somatosensory_cortex_R ~ condition, data = df_cent)
t.test(Oral_somatosensory_cortex_L ~ condition, data = df_cent)
t.test(Precuneus_L ~ condition, data = df_cent)
t.test(Precuneus_R ~ condition, data = df_cent)
t.test(Ventral_striatum_L ~ condition, data = df_cent)
t.test(Ventral_striatum_R ~ condition, data = df_cent)
t.test(vlPFC_L ~ condition, data = df_cent)
t.test(vlPFC_R ~ condition, data = df_cent)
t.test(vlThalamus_L ~ condition, data = df_cent)
t.test(vlThalamus_R ~ condition, data = df_cent)
t.test(vmPFC_L ~ condition, data = df_cent)
t.test(vmPFC_R ~ condition, data = df_cent)
#sink()


#Test module clustering and centrality
#read-in the behavioral data
df2 <- read.csv("/Users/jennygilbert/Google Drive/NIBL/Projects/18-0417 BeveL/data/paper_specific/betaseries/behavioral_data/betaseries_sample_november_update.csv", sep = ',')
print(df2$ID)

#Remove the blank lines added at the end (no clue why this happens)
dat <- df2[-c(86,87), ]
print(dat$ID)
names(dat)
## Test for significant correlation between module metrics and behavioral data
#No meaningful relationship with pleasantness for sweet 
cor.test(dat$module0_clustering_reward, dat$sweetstim_pleasent)
cor.test(dat$module1_clustering_reward, dat$sweetstim_pleasent)
cor.test(dat$module2_clustering_reward, dat$sweetstim_pleasent)
cor.test(dat$module3_clustering_reward, dat$sweetstim_pleasent)
cor.test(dat$module4_clustering_reward, dat$sweetstim_pleasent)
cor.test(dat$module5_clustering_reward, dat$sweetstim_pleasent)
cor.test(dat$module6_clustering_reward, dat$sweetstim_pleasent)
cor.test(dat$module7_clustering_reward, dat$sweetstim_pleasent)
cor.test(dat$module8_clustering_reward, dat$sweetstim_pleasent)

cor.test(dat$module0_centrality_reward, dat$sweetstim_pleasent)
cor.test(dat$module1_centrality_reward, dat$sweetstim_pleasent)
cor.test(dat$module2_centrality_reward, dat$sweetstim_pleasent)
cor.test(dat$module3_centrality_reward, dat$sweetstim_pleasent)
cor.test(dat$module4_centrality_reward, dat$sweetstim_pleasent)
cor.test(dat$module5_centrality_reward, dat$sweetstim_pleasent)
cor.test(dat$module6_centrality_reward, dat$sweetstim_pleasent)
cor.test(dat$module7_centrality_reward, dat$sweetstim_pleasent)
cor.test(dat$module8_centrality_reward, dat$sweetstim_pleasent)

#No relation to pleasentness for bitter
cor.test(dat$module0_clustering_punish, dat$bitterstim_pleasent)
cor.test(dat$module1_clustering_punish, dat$bitterstim_pleasent)
cor.test(dat$module2_clustering_punish, dat$bitterstim_pleasent)
cor.test(dat$module3_clustering_punish, dat$bitterstim_pleasent)
cor.test(dat$module4_clustering_punish, dat$bitterstim_pleasent)
cor.test(dat$module5_clustering_punish, dat$bitterstim_pleasent)
cor.test(dat$module6_clustering_punish, dat$bitterstim_pleasent)
cor.test(dat$module7_clustering_punish, dat$bitterstim_pleasent)
cor.test(dat$module8_clustering_punish, dat$bitterstim_pleasent)

cor.test(dat$module0_centrality_punish, dat$bitterstim_pleasent)
cor.test(dat$module1_centrality_punish, dat$bitterstim_pleasent)
cor.test(dat$module2_centrality_punish, dat$bitterstim_pleasent)
cor.test(dat$module3_centrality_punish, dat$bitterstim_pleasent)
cor.test(dat$module4_centrality_punish, dat$bitterstim_pleasent)
cor.test(dat$module5_centrality_punish, dat$bitterstim_pleasent)
cor.test(dat$module6_centrality_punish, dat$bitterstim_pleasent)
cor.test(dat$module7_centrality_punish, dat$bitterstim_pleasent)
cor.test(dat$module8_centrality_punish, dat$bitterstim_pleasent)

### TEST FOR DESIRE
cor.test(dat$module0_clustering_reward, dat$sweetstim_desire)
cor.test(dat$module1_clustering_reward, dat$sweetstim_desire)
cor.test(dat$module2_clustering_reward, dat$sweetstim_desire)
cor.test(dat$module3_clustering_reward, dat$sweetstim_desire)
cor.test(dat$module4_clustering_reward, dat$sweetstim_desire)
cor.test(dat$module5_clustering_reward, dat$sweetstim_desire)
cor.test(dat$module6_clustering_reward, dat$sweetstim_desire)
cor.test(dat$module7_clustering_reward, dat$sweetstim_desire)
cor.test(dat$module8_clustering_reward, dat$sweetstim_desire)

cor.test(dat$module0_centrality_reward, dat$sweetstim_desire)
cor.test(dat$module1_centrality_reward, dat$sweetstim_desire)
cor.test(dat$module2_centrality_reward, dat$sweetstim_desire)
cor.test(dat$module3_centrality_reward, dat$sweetstim_desire)
cor.test(dat$module4_centrality_reward, dat$sweetstim_desire)
cor.test(dat$module5_centrality_reward, dat$sweetstim_desire)
cor.test(dat$module6_centrality_reward, dat$sweetstim_desire)
cor.test(dat$module7_centrality_reward, dat$sweetstim_desire)
cor.test(dat$module8_centrality_reward, dat$sweetstim_desire)
### THIS IS CONSISTENTLY RELATED, BUT ONLY CLUSTERING IN 7 PASSES BONFERRONI


#No relation to desire for bitter
cor.test(dat$module0_clustering_punish, dat$bitterstim_desire)
cor.test(dat$module1_clustering_punish, dat$bitterstim_desire)
cor.test(dat$module2_clustering_punish, dat$bitterstim_desire)
cor.test(dat$module3_clustering_punish, dat$bitterstim_desire)
cor.test(dat$module4_clustering_punish, dat$bitterstim_desire)
cor.test(dat$module5_clustering_punish, dat$bitterstim_desire)
cor.test(dat$module6_clustering_punish, dat$bitterstim_desire)
cor.test(dat$module7_clustering_punish, dat$bitterstim_desire)
cor.test(dat$module8_clustering_punish, dat$bitterstim_desire)

cor.test(dat$module0_centrality_punish, dat$bitterstim_desire)
cor.test(dat$module1_centrality_punish, dat$bitterstim_desire)
cor.test(dat$module2_centrality_punish, dat$bitterstim_desire)
cor.test(dat$module3_centrality_punish, dat$bitterstim_desire)
cor.test(dat$module4_centrality_punish, dat$bitterstim_desire)
cor.test(dat$module5_centrality_punish, dat$bitterstim_desire)
cor.test(dat$module6_centrality_punish, dat$bitterstim_desire)
cor.test(dat$module7_centrality_punish, dat$bitterstim_desire)
cor.test(dat$module8_centrality_punish, dat$bitterstim_desire)

#Module parameters relates to Sweet Stim Level
res.aov <- aov(module0_clustering_reward ~ sweetstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module1_clustering_reward ~ sweetstim_level, data = dat)
summary(res.aov)
#^^^ SIGNIFICANT
res.aov <- aov(module2_clustering_reward ~ sweetstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module3_clustering_reward ~ sweetstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module4_clustering_reward ~ sweetstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module5_clustering_reward ~ sweetstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module6_clustering_reward ~ sweetstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module7_clustering_reward ~ sweetstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module8_clustering_reward ~ sweetstim_level, data = dat)
summary(res.aov)

res.aov <- aov(module0_centrality_reward ~ sweetstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module1_centrality_reward ~ sweetstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module2_centrality_reward ~ sweetstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module3_centrality_reward ~ sweetstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module4_centrality_reward ~ sweetstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module5_centrality_reward ~ sweetstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module6_centrality_reward ~ sweetstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module7_centrality_reward ~ sweetstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module8_centrality_reward ~ sweetstim_level, data = dat)
summary(res.aov)

# Doesnt matter for the punishment 
res.aov <- aov(module0_clustering_punish ~ bitterstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module1_clustering_punish ~ bitterstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module2_clustering_punish ~ bitterstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module3_clustering_punish ~ bitterstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module4_clustering_punish ~ bitterstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module5_clustering_punish ~ bitterstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module6_clustering_punish ~ bitterstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module7_clustering_punish ~ bitterstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module8_clustering_punish ~ bitterstim_level, data = dat)
summary(res.aov)

res.aov <- aov(module0_centrality_punish ~ bitterstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module1_centrality_punish ~ bitterstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module2_centrality_punish ~ bitterstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module3_centrality_punish ~ bitterstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module4_centrality_punish ~ bitterstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module5_centrality_punish ~ bitterstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module6_centrality_punish ~ bitterstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module7_centrality_punish ~ bitterstim_level, data = dat)
summary(res.aov)
res.aov <- aov(module8_centrality_punish ~ bitterstim_level, data = dat)
summary(res.aov)

names(dat)

#BMI
cor.test(dat$module0_clustering_reward, dat$BMI)
cor.test(dat$module1_clustering_reward, dat$BMI)
cor.test(dat$module2_clustering_reward, dat$BMI)
cor.test(dat$module3_clustering_reward, dat$BMI)
cor.test(dat$module4_clustering_reward, dat$BMI)
cor.test(dat$module5_clustering_reward, dat$BMI)
cor.test(dat$module6_clustering_reward, dat$BMI)
cor.test(dat$module7_clustering_reward, dat$BMI)
cor.test(dat$module8_clustering_reward, dat$BMI)

#BMI?
cor.test(dat$module0_clustering_punish, dat$BMI)
cor.test(dat$module1_clustering_punish, dat$BMI)
cor.test(dat$module2_clustering_punish, dat$BMI)
cor.test(dat$module3_clustering_punish, dat$BMI)
cor.test(dat$module4_clustering_punish, dat$BMI)
cor.test(dat$module5_clustering_punish, dat$BMI)
cor.test(dat$module6_clustering_punish, dat$BMI)
cor.test(dat$module7_clustering_punish, dat$BMI)
cor.test(dat$module8_clustering_punish, dat$BMI)

cor.test(dat$module0_centrality_reward, dat$BMI)
cor.test(dat$module1_centrality_reward, dat$BMI)
cor.test(dat$module2_centrality_reward, dat$BMI)
cor.test(dat$module3_centrality_reward, dat$BMI)
cor.test(dat$module4_centrality_reward, dat$BMI)
cor.test(dat$module5_centrality_reward, dat$BMI)
cor.test(dat$module6_centrality_reward, dat$BMI)
cor.test(dat$module7_centrality_reward, dat$BMI)
cor.test(dat$module8_centrality_reward, dat$BMI)

#BMI? 
cor.test(dat$module0_centrality_punish, dat$BMI)
cor.test(dat$module1_centrality_punish, dat$BMI)
cor.test(dat$module2_centrality_punish, dat$BMI)
cor.test(dat$module3_centrality_punish, dat$BMI)
cor.test(dat$module4_centrality_punish, dat$BMI)
cor.test(dat$module5_centrality_punish, dat$BMI)
cor.test(dat$module6_centrality_punish, dat$BMI)
cor.test(dat$module7_centrality_punish, dat$BMI)
cor.test(dat$module8_centrality_punish, dat$BMI)

#external_eating and reward? 
cor.test(dat$module0_clustering_reward, dat$external_eating)
cor.test(dat$module1_clustering_reward, dat$external_eating)
cor.test(dat$module2_clustering_reward, dat$external_eating)
cor.test(dat$module3_clustering_reward, dat$external_eating)
cor.test(dat$module4_clustering_reward, dat$external_eating)
cor.test(dat$module5_clustering_reward, dat$external_eating)
cor.test(dat$module6_clustering_reward, dat$external_eating)
cor.test(dat$module7_clustering_reward, dat$external_eating)
cor.test(dat$module8_clustering_reward, dat$external_eating)

cor.test(dat$module0_centrality_reward, dat$external_eating)
cor.test(dat$module1_centrality_reward, dat$external_eating)
cor.test(dat$module2_centrality_reward, dat$external_eating)
cor.test(dat$module3_centrality_reward, dat$external_eating)
cor.test(dat$module4_centrality_reward, dat$external_eating)
cor.test(dat$module5_centrality_reward, dat$external_eating)
cor.test(dat$module6_centrality_reward, dat$external_eating)
cor.test(dat$module7_centrality_reward, dat$external_eating)
cor.test(dat$module8_centrality_reward, dat$external_eating)

#external_eating and punishment?
cor.test(dat$module0_clustering_punish, dat$external_eating)
cor.test(dat$module1_clustering_punish, dat$external_eating)
cor.test(dat$module2_clustering_punish, dat$external_eating)
cor.test(dat$module3_clustering_punish, dat$external_eating)
cor.test(dat$module4_clustering_punish, dat$external_eating)
cor.test(dat$module5_clustering_punish, dat$external_eating)
cor.test(dat$module6_clustering_punish, dat$external_eating)
cor.test(dat$module7_clustering_punish, dat$external_eating)
cor.test(dat$module8_clustering_punish, dat$external_eating)

cor.test(dat$module0_centrality_punish, dat$external_eating)
cor.test(dat$module1_centrality_punish, dat$external_eating)
cor.test(dat$module2_centrality_punish, dat$external_eating)
cor.test(dat$module3_centrality_punish, dat$external_eating)
cor.test(dat$module4_centrality_punish, dat$external_eating)
cor.test(dat$module5_centrality_punish, dat$external_eating)
cor.test(dat$module6_centrality_punish, dat$external_eating)
cor.test(dat$module7_centrality_punish, dat$external_eating)
cor.test(dat$module8_centrality_punish, dat$external_eating)

#nback_accuracy and reward? 
cor.test(dat$module0_clustering_reward, dat$nback_accuracy)
cor.test(dat$module1_clustering_reward, dat$nback_accuracy)
cor.test(dat$module2_clustering_reward, dat$nback_accuracy)
cor.test(dat$module3_clustering_reward, dat$nback_accuracy)
cor.test(dat$module4_clustering_reward, dat$nback_accuracy)
cor.test(dat$module5_clustering_reward, dat$nback_accuracy)
cor.test(dat$module6_clustering_reward, dat$nback_accuracy)
cor.test(dat$module7_clustering_reward, dat$nback_accuracy)
cor.test(dat$module8_clustering_reward, dat$nback_accuracy)

cor.test(dat$module0_centrality_reward, dat$nback_accuracy)
cor.test(dat$module1_centrality_reward, dat$nback_accuracy)
cor.test(dat$module2_centrality_reward, dat$nback_accuracy)
cor.test(dat$module3_centrality_reward, dat$nback_accuracy)
cor.test(dat$module4_centrality_reward, dat$nback_accuracy)
cor.test(dat$module5_centrality_reward, dat$nback_accuracy)
cor.test(dat$module6_centrality_reward, dat$nback_accuracy)
cor.test(dat$module7_centrality_reward, dat$nback_accuracy)
cor.test(dat$module8_centrality_reward, dat$nback_accuracy)

cor.test(dat$module0_clustering_punish, dat$nback_accuracy)
cor.test(dat$module1_clustering_punish, dat$nback_accuracy)
cor.test(dat$module2_clustering_punish, dat$nback_accuracy)
cor.test(dat$module3_clustering_punish, dat$nback_accuracy)
cor.test(dat$module4_clustering_punish, dat$nback_accuracy)
cor.test(dat$module5_clustering_punish, dat$nback_accuracy)
cor.test(dat$module6_clustering_punish, dat$nback_accuracy)
cor.test(dat$module7_clustering_punish, dat$nback_accuracy)
cor.test(dat$module8_clustering_punish, dat$nback_accuracy)

cor.test(dat$module0_centrality_punish, dat$nback_accuracy)
cor.test(dat$module1_centrality_punish, dat$nback_accuracy)
cor.test(dat$module2_centrality_punish, dat$nback_accuracy)
cor.test(dat$module3_centrality_punish, dat$nback_accuracy)
cor.test(dat$module4_centrality_punish, dat$nback_accuracy)
cor.test(dat$module5_centrality_punish, dat$nback_accuracy)
cor.test(dat$module6_centrality_punish, dat$nback_accuracy)
cor.test(dat$module7_centrality_punish, dat$nback_accuracy)
cor.test(dat$module8_centrality_punish, dat$nback_accuracy)

#DRES and reward? 
cor.test(dat$module0_clustering_reward, dat$DRES)
cor.test(dat$module1_clustering_reward, dat$DRES)
cor.test(dat$module2_clustering_reward, dat$DRES)
cor.test(dat$module3_clustering_reward, dat$DRES)
cor.test(dat$module4_clustering_reward, dat$DRES)
cor.test(dat$module5_clustering_reward, dat$DRES)
cor.test(dat$module6_clustering_reward, dat$DRES)
cor.test(dat$module7_clustering_reward, dat$DRES)
cor.test(dat$module8_clustering_reward, dat$DRES)

cor.test(dat$module0_centrality_reward, dat$DRES)
cor.test(dat$module1_centrality_reward, dat$DRES)
cor.test(dat$module2_centrality_reward, dat$DRES)
cor.test(dat$module3_centrality_reward, dat$DRES)
cor.test(dat$module4_centrality_reward, dat$DRES)
cor.test(dat$module5_centrality_reward, dat$DRES)
cor.test(dat$module6_centrality_reward, dat$DRES)
cor.test(dat$module7_centrality_reward, dat$DRES)
cor.test(dat$module8_centrality_reward, dat$DRES)

cor.test(dat$module0_clustering_punish, dat$DRES)
cor.test(dat$module1_clustering_punish, dat$DRES)
cor.test(dat$module2_clustering_punish, dat$DRES)
cor.test(dat$module3_clustering_punish, dat$DRES)
cor.test(dat$module4_clustering_punish, dat$DRES)
cor.test(dat$module5_clustering_punish, dat$DRES)
cor.test(dat$module6_clustering_punish, dat$DRES)
cor.test(dat$module7_clustering_punish, dat$DRES)
cor.test(dat$module8_clustering_punish, dat$DRES)

cor.test(dat$module0_centrality_punish, dat$DRES)
cor.test(dat$module1_centrality_punish, dat$DRES)
cor.test(dat$module2_centrality_punish, dat$DRES)
cor.test(dat$module3_centrality_punish, dat$DRES)
cor.test(dat$module4_centrality_punish, dat$DRES)
cor.test(dat$module5_centrality_punish, dat$DRES)
cor.test(dat$module6_centrality_punish, dat$DRES)
cor.test(dat$module7_centrality_punish, dat$DRES)
cor.test(dat$module8_centrality_punish, dat$DRES)


#Plot
plot(dat$module7_clustering_reward, dat$sweetstim_desire,
     xlab="Clustering Coefficient", ylab="VAS Rating of Desire for Sweet Beverage")
abline(lm(dat$sweetstim_desire ~ dat$module7_clustering_reward))

#points(dat$module2_punishment_clustering, dat$sensitivity_punish, col=2)
#points(dat$module3_punishment_clustering, dat$sensitivity_punish, col=3)
#points(dat$module4_punishment_clustering, dat$sensitivity_punish, col=4)
#legend("topright", inset=.05, title="Module",
#       c("1","2","3","4"), fill=c('black', "red", "green", "blue"))



#abline(lm(dat$sensitivity_punish ~dat$module2_punishment_clustering), col = "red")
#abline(lm(dat$sensitivity_punish ~dat$module3_punishment_clustering), col = "green")
#abline(lm(dat$sensitivity_punish ~dat$module4_punishment_clustering), col = "blue")

plot(dat$module1_punishment_centrality, dat$sensitivity_punish,
     xlab="Betweenness Centrality", ylab="% Sensitivity to Punishment", xlim=c(0, 0.1))
points(dat$module2_punishment_centrality, dat$sensitivity_punish, col=2)
points(dat$module3_punishment_centrality, dat$sensitivity_punish, col=3)
points(dat$module4_punishment_centrality, dat$sensitivity_punish, col=4)
legend("topright", inset=.05, title="Module",
       c("1","2","3","4"), fill=c('black', "red", "green", "blue"))

abline(lm(dat$sensitivity_punish ~dat$module1_punishment_centrality))
abline(lm(dat$sensitivity_punish ~dat$module2_punishment_centrality), col = "red")
abline(lm(dat$sensitivity_punish ~dat$module3_punishment_centrality), col = "green")
abline(lm(dat$sensitivity_punish ~dat$module4_punishment_centrality), col = "blue")



