library(readxl)
library(ggplot2)
library(psych)
library(plyr)
library(lmer)
library(reshape2)


sink('/Users/jennygilbert/Documents/betaseries_bevel/5_analysis/results/node_analysis_output.txt')

df <- read.csv("/Users/jennygilbert/Documents/betaseries_bevel/5_analysis/results/node_metrics_by_sub.csv")
names(df)

describe(df)

df_long <- read.csv("/Users/jennygilbert/Documents/betaseries_bevel/5_analysis/results/node_metrics_by_sub_long.csv")
names(df_long)


#Select Clustering
df_clust <- df_long[which(df_long$metric == 'clustering'), ]

t.test(Amygdala_L ~ condition, data = df_clust)
t.test(Amygdala_R ~ condition, data = df_clust)
t.test(Dorsal_striatum_L ~ condition, data = df_clust)
t.test(Dorsal_striatum_R ~ condition, data = df_clust)
t.test(Fusiform_gyrus_L ~ condition, data = df_clust)
t.test(Fusiform_gyrus_R ~ condition, data = df_clust)
t.test(Hippocampus_L ~ condition, data = df_clust)
t.test(Hippocampus_R ~ condition, data = df_clust)
t.test(Insula_L ~ condition, data = df_clust)
t.test(Insula_R ~ condition, data = df_clust)
t.test(Intracalcarine_cortex_L ~ condition, data = df_clust)
t.test(Intracalcarine_cortex_R ~ condition, data = df_clust)
t.test(lOFC_L ~ condition, data = df_clust)
t.test(lOFC_R ~ condition, data = df_clust)
t.test(mOFC_L ~ condition, data = df_clust)
t.test(mOFC_R ~ condition, data = df_clust)
t.test(Oral_somatosensory_cortex_R ~ condition, data = df_clust)
t.test(Oral_somatosensory_cortex_L ~ condition, data = df_clust)
t.test(Precuneus_L ~ condition, data = df_clust)
t.test(Precuneus_R ~ condition, data = df_clust)
t.test(Ventral_striatum_L ~ condition, data = df_clust)
t.test(Ventral_striatum_R ~ condition, data = df_clust)
t.test(vlPFC_L ~ condition, data = df_clust)
t.test(vlPFC_R ~ condition, data = df_clust)
t.test(vlThalamus_L ~ condition, data = df_clust)
t.test(vlThalamus_R ~ condition, data = df_clust)
t.test(vmPFC_L ~ condition, data = df_clust)
t.test(vmPFC_R ~ condition, data = df_clust)

#Select Centrality
df_cent <- df_long[which(df_long$metric == 'centrality'), ]
describe(df_cent)

t.test(Amygdala_L ~ condition, data = df_cent)
t.test(Amygdala_L ~ condition, data = df_cent)
t.test(Amygdala_R ~ condition, data = df_cent)
t.test(Dorsal_striatum_L ~ condition, data = df_cent)
t.test(Dorsal_striatum_R ~ condition, data = df_cent)
t.test(Fusiform_gyrus_L ~ condition, data = df_cent)
t.test(Fusiform_gyrus_R ~ condition, data = df_cent)
t.test(Hippocampus_L ~ condition, data = df_cent)
t.test(Hippocampus_R ~ condition, data = df_cent)
t.test(Insula_L ~ condition, data = df_cent)
t.test(Insula_R ~ condition, data = df_cent)
t.test(Intracalcarine_cortex_L ~ condition, data = df_cent)
t.test(Intracalcarine_cortex_R ~ condition, data = df_cent)
t.test(lOFC_L ~ condition, data = df_cent)
t.test(lOFC_R ~ condition, data = df_cent)
t.test(mOFC_L ~ condition, data = df_cent)
t.test(mOFC_R ~ condition, data = df_cent)
t.test(Oral_somatosensory_cortex_R ~ condition, data = df_cent)
t.test(Oral_somatosensory_cortex_L ~ condition, data = df_cent)
t.test(Precuneus_L ~ condition, data = df_cent)
t.test(Precuneus_R ~ condition, data = df_cent)
t.test(Ventral_striatum_L ~ condition, data = df_cent)
t.test(Ventral_striatum_R ~ condition, data = df_cent)
t.test(vlPFC_L ~ condition, data = df_cent)
t.test(vlPFC_R ~ condition, data = df_cent)
t.test(vlThalamus_L ~ condition, data = df_cent)
t.test(vlThalamus_R ~ condition, data = df_cent)
t.test(vmPFC_L ~ condition, data = df_cent)
t.test(vmPFC_R ~ condition, data = df_cent)

sink()